version: 2
updates:
  # npm packages
  - package-ecosystem: 'npm'
    directory: '/app/main'
    schedule:
      interval: 'monthly'
    commit-message:
      prefix: 'deps(main-npm): '
    groups:
      dependencies:
        patterns:
          - '*'

  # rust packages
  - package-ecosystem: 'cargo'
    directory: '/core_lib'
    schedule:
      interval: 'monthly'
    commit-message:
      prefix: 'deps(core_lib): '
    groups:
      dependencies:
        patterns:
          - '*'

  - package-ecosystem: 'cargo'
    directory: '/app/main/src-tauri'
    schedule:
      interval: 'monthly'
    commit-message:
      prefix: 'deps(main-rust): '
    groups:
      dependencies:
        patterns:
          - '*'

  # github actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: monthly
    commit-message:
      prefix: 'deps(actions): '
    groups:
      dependencies:
        patterns:
          - '*'
