name: Lint

on:
  push:
    branches: [ "main" ]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: [ "./core_lib", "./app/main/src-tauri" ]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.97.1
        with:
          components: rustfmt
      - run: |
          cd ${{ matrix.directory }}
          cargo fmt --all --check

  clippy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.97.1
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
        with:
          cache-directories: "${{ github.workspace }}/core_lib/target"
      - uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libdbus-1-dev
      - run: |
          cd core_lib
          cargo clippy --all-features
